[package]
name = "bevy_proto_aseprite"
version = "0.1.0"
authors = ["alpine_alpaca <alpine.alpaca.games@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5"
asefile = "0.2"
anyhow = "1.0"

[dev-dependencies]
strum = { version = "0.20", features = ["derive"] }

[profile.dev.package."*"]
opt-level = 2
