[package]
name = "bevy_ase"
version = "0.1.0"
authors = ["alpine_alpaca <alpine.alpaca.games@gmail.com>", "B-Reif"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5"
asefile = { git = "https://github.com/B-Reif/asefile", branch = "main" }
anyhow = "1.0"

[dev-dependencies]
strum = { version = "0.20", features = ["derive"] }
# benimator is used in the 'simple' example
benimator = "0.3.0"
bevy_sprite = { version = "^0.5.0", default-features = false }
# bevy_ecs_tilemap is used in the 'tilemap' example
bevy_ecs_tilemap = "0.4"

[profile.dev.package."*"]
opt-level = 2
